modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="hbm"
version="1.0.0"
displayName="HBM's NTM - Not Deluxe Edition"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="bufka, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.hbm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



